// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHqKPyMpTVr71WNJvK_rwGybEC1dMpd8E',
    appId: '1:83752296800:web:4d530de92065b5911bfe05',
    messagingSenderId: '83752296800',
    projectId: 'new-latest-purvan',
    authDomain: 'new-latest-purvan.firebaseapp.com',
    storageBucket: 'new-latest-purvan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjb2Dn9CnlGx77xsMZ-hWpIpNKG7KN2Uc',
    appId: '1:83752296800:android:975f27137b5a5e731bfe05',
    messagingSenderId: '83752296800',
    projectId: 'new-latest-purvan',
    storageBucket: 'new-latest-purvan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAjahuL6Til4l2FqqesZkq-s3ZV7M88H4',
    appId: '1:83752296800:ios:e6c774f911603cba1bfe05',
    messagingSenderId: '83752296800',
    projectId: 'new-latest-purvan',
    storageBucket: 'new-latest-purvan.appspot.com',
    iosBundleId: 'com.example.purva',
  );
}
